name: Pull Request Stats

on:
  schedule:
    - cron: '12 1 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        id: prstats
        uses: flowwer-dev/pull-request-stats@v2.9.0
        with:
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
          organization: 'kubeservice-stack'
          period: 7
          charts: false
          disable-links: true
          sort-by: 'COMMENTS'
