name: Pull Request Stats

on:
  schedule:
    - cron: '12 1 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        id: prstats
        uses: flowwer-dev/pull-request-stats@v2.9.0
        with:
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
          organization: 'kubeservice-stack'
          period: 7
          charts: false
          disable-links: true
          sort-by: 'COMMENTS'
      - run: |
          cat << EOF
          result: ${{ steps.prstats.outputs.data }}
          EOF
      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@v1.4.4
        with:
          path: profile/README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{steps.prstats.outputs.data}}
          openDelimiter: "<!--REVIEWS-->"
          closeDelimiter: "<!--REVIEWS-END-->"
